CHECK ASSERTION HOUSE_STREET_DISJOINT;

CHECK ASSERTION HOUSE_HOUSE_DISJOINT;

CHECK ASSERTION HOUSE_LAKE_DISJOINT;

CHECK ASSERTION STREET_LAKE_DISJOINT;

CHECK ASSERTION STREET_LANDUSE_DISJOINT;

CHECK ASSERTION STREET_PLAYGROUND_DISJOINT;

CHECK ASSERTION NO_STANDALONE_STOP;

CHECK ASSERTION TRAFFIC_LIGHT_AT_STREET;

CHECK ASSERTION PARKING_REACHABLE;
