DROP ASSERTION HOUSE_STREET_DISJOINT;

DROP ASSERTION HOUSE_HOUSE_DISJOINT;

DROP ASSERTION HOUSE_LAKE_DISJOINT;

DROP ASSERTION STREET_LAKE_DISJOINT;

DROP ASSERTION STREET_LANDUSE_DISJOINT;

DROP ASSERTION STREET_PLAYGROUND_DISJOINT;

DROP ASSERTION NO_STANDALONE_STOP;

DROP ASSERTION TRAFFIC_LIGHT_AT_STREET;

DROP ASSERTION PARKING_REACHABLE;

