CREATE ASSERTION HOUSE_STREET_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Haus AS h, Strasse AS s
        WHERE path(h.umriss) ?# s.verlauf
    )
);

CREATE ASSERTION HOUSE_HOUSE_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Haus AS h1, Haus AS h2
        WHERE h1.umriss && h2.umriss
    )
);

CREATE ASSERTION HOUSE_LAKE_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Haus AS h, See AS l
        WHERE h.umriss && l.umriss
    )
);

CREATE ASSERTION STREET_LAKE_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Strasse AS s, See AS l
        WHERE s.verlauf ?# path(l.umriss)
    )
);

CREATE ASSERTION STREET_LANDUSE_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Strasse AS s, Landnutzung AS l
        WHERE s.verlauf ?# path(l.umriss)
    )
);

CREATE ASSERTION STREET_PLAYGROUND_DISJOINT CHECK (
    NOT EXISTS ( SELECT * FROM
        Strasse AS s, Spielplatz AS p
        WHERE s.verlauf ?# path(p.umriss)
    )
);

CREATE ASSERTION NO_STANDALONE_STOP CHECK (
    NOT EXISTS ( SELECT * FROM
        Haltestelle AS b
        WHERE NOT EXISTS ( SELECT * FROM
            Strasse AS s
            WHERE approx_circle(b.position, 1) ?# s.verlauf
        )
    )
);

CREATE ASSERTION TRAFFIC_LIGHT_AT_STREET CHECK (
    NOT EXISTS ( SELECT * FROM
        Ampel AS t
        WHERE NOT EXISTS ( SELECT * FROM
            Strasse AS s
            WHERE approx_circle(t.position, 1) ?# s.verlauf
        )
    )
);

CREATE ASSERTION PARKING_REACHABLE CHECK (
    NOT EXISTS ( SELECT * FROM
        Parkplatz AS p
        WHERE NOT EXISTS ( SELECT * FROM
            Strasse AS s
            WHERE approx_circle(center(circle(p.umriss)), radius(circle(p.umriss)) + 1.0) ?# s.verlauf
        )
    )
);
